# Generated by Django 5.0.3 on 2024-04-13 14:46

import core.models
import stdimage.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_produto_icone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='icone',
            field=stdimage.models.StdImageField(force_min_size=False, upload_to=core.models.get_file_path, variations={'thumb': {'crop': False, 'height': 800, 'width': 800}}, verbose_name='Icone'),
        ),
    ]
